# Generated by Django 3.2.3 on 2021-06-15 18:29

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotasIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_index', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Preco')),
                ('titulo', models.CharField(max_length=10000, verbose_name='Titulo')),
                ('texto_promocao', models.CharField(max_length=100000, verbose_name='Texto')),
            ],
        ),
        migrations.CreateModel(
            name='NovaColecaoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_index', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Preco')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Titulo')),
                ('titulo2', models.CharField(max_length=1000, verbose_name='Titulo 2')),
                ('preco2', models.DecimalField(decimal_places=2, max_digits=10000, verbose_name='Preco 2')),
                ('foto_index2', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='imagem 2')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosIndexPrimeiraColuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_tenis', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Preco')),
                ('nome_tenis', models.CharField(max_length=10000, verbose_name='Nome do Tenis')),
            ],
        ),
    ]
