# Generated by Django 3.2.3 on 2021-06-11 21:27

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovaColecaoIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_colecao', models.TextField(max_length=1000, verbose_name='Texto')),
                ('foto_index', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=109309130190, verbose_name='Preco')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Titulo')),
            ],
        ),
    ]
