# Generated by Django 3.2.3 on 2021-06-11 21:41

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotasIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_colecao', models.TextField(max_length=1000, verbose_name='Texto')),
                ('foto_index', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=109309130190, verbose_name='Preco')),
                ('titulo', models.CharField(max_length=1000, verbose_name='Titulo')),
            ],
        ),
        migrations.CreateModel(
            name='NovosProdutosIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_titulo', models.CharField(max_length=1000, verbose_name='Pre Titulo')),
                ('pre_texto', models.TextField(max_length=1000, verbose_name='Texto')),
                ('foto_tenis', stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='imagem')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=109309130190, verbose_name='Preco')),
                ('nome_tenis', models.CharField(max_length=1000, verbose_name='Nome do Tenis')),
            ],
        ),
    ]
