# Generated by Django 3.2.3 on 2021-06-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210615_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novacolecaoindex',
            name='preco',
            field=models.DecimalField(decimal_places=0, max_digits=1000, verbose_name='Preco'),
        ),
    ]
