# Generated by Django 3.2.3 on 2021-06-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botasindex_novosprodutosindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novosprodutosindex',
            name='pre_texto',
        ),
        migrations.RemoveField(
            model_name='novosprodutosindex',
            name='pre_titulo',
        ),
    ]
