# Generated by Django 3.2.3 on 2021-06-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210611_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NovosProdutosIndex',
            new_name='ProdutosIndexPrimeiraColuna',
        ),
    ]
