# Generated by Django 3.2.3 on 2021-06-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_produtosindexsegundacoluna'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutosIndexSegundaColuna',
        ),
    ]
