# Generated by Django 3.2.3 on 2021-06-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_produtosindexsegundacoluna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novacolecaoindex',
            name='texto_colecao',
            field=models.TextField(editable=False, max_length=1000, verbose_name='Texto'),
        ),
    ]
