# Generated by Django 3.2.3 on 2021-06-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_novacolecaoindex_texto_colecao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botasindex',
            name='texto_colecao',
        ),
        migrations.AddField(
            model_name='produtosindexprimeiracoluna',
            name='texto_colecao',
            field=models.TextField(default=2, max_length=1000, verbose_name='Texto'),
            preserve_default=False,
        ),
    ]
