# Generated by Django 3.2.3 on 2021-06-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210613_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novacolecaoindex',
            name='texto_colecao',
        ),
        migrations.RemoveField(
            model_name='produtosindexprimeiracoluna',
            name='texto_colecao',
        ),
    ]
