# Generated by Django 3.2.3 on 2021-06-14 14:46

import core.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210613_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novacolecaoindex',
            name='foto_index2',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_path, verbose_name='imagem 2'),
        ),
        migrations.AlterField(
            model_name='novacolecaoindex',
            name='preco2',
            field=models.DecimalField(decimal_places=2, max_digits=109309130190, verbose_name='Preco 2'),
        ),
        migrations.AlterField(
            model_name='novacolecaoindex',
            name='titulo2',
            field=models.CharField(max_length=1000, verbose_name='Titulo 2'),
        ),
    ]
