# Generated by Django 3.2.3 on 2021-06-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210614_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='botasindex',
            name='texto_promocao',
            field=models.CharField(default=2, max_length=10220202, verbose_name='Texto'),
            preserve_default=False,
        ),
    ]
