# Generated by Django 3.2.3 on 2021-06-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_botasindex_texto_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botasindex',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10930000, verbose_name='Preco'),
        ),
    ]
