# Generated by Django 3.2.3 on 2021-06-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_botasindex_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novacolecaoindex',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=109000000000, verbose_name='Preco'),
        ),
        migrations.AlterField(
            model_name='novacolecaoindex',
            name='preco2',
            field=models.DecimalField(decimal_places=2, max_digits=109300000000, verbose_name='Preco 2'),
        ),
        migrations.AlterField(
            model_name='produtosindexprimeiracoluna',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10930000000, verbose_name='Preco'),
        ),
    ]
