# Generated by Django 3.2.3 on 2021-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210615_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botasindex',
            name='texto_promocao',
            field=models.CharField(max_length=10220000, verbose_name='Texto'),
        ),
    ]
